### ISSUE TITLE
Discord link invalid & some functions missing

### ISSUE THREAD

**Issue by zReeved** [Blyrex/Velocity-Bungeecord-Bridge#3]
Log: https://hastebin.com/ximusajeja.less
As it looks, two plugins need the java.lang.NoSuchMethodError method: 'net.md_5.bungee.BungeeCord net.md_5.bungee.BungeeCord.getInstance()' 
One the java.lang.ClassNotFoundException: net.md_5.bungee.netty.PipelineUtils method. 
And protocolize (protocollib for bungeecord) has problems with it I think, but everything else works. Find the project very noteworthy.

**Comment by 0utplay** [comment]
Hey thanks for your time!

We are going to look into this

**Comment by Blyrex** [comment]
Hi, the BungeeCord.getInstance() Method should be fixed

**Comment by zKaanGit** [comment]
Okay, but I think something isnt working. In line 3 is an error with BungeeCord.getInstance().
And these errors are still persistent. https://pastebin.com/SdF6MP0s
And I can't build the project with lombok 1.18.16, I used 1.18.20 and it works. Only for information.

**Comment by 0utplay** [comment]
I am back from vacation and will have a look at those issues. Thanks for the report

**Comment by zKaanGit** [comment]
Okay, thanks would be awesome
